config/routes.rb
Bookbook::Application.routes.draw do
  get "catalog/index"

  get "catalog/show"

  get "catalog/search"

  get "catalog/latest"

  resources :books

  resources :publishers

  get "about/index"

  resources :authors

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books
  validates_presence_of :first_name, :last_name
  def name
    "#{first_name} #{last_name}"
  end
end

app/models/authors_book.rb
class AuthorsBook < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :publisher
  has_and_belongs_to_many :authors
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books
  validates_length_of :publisher, :in => 2..255
  validates_uniqueness_of :publisher
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
    @page_title = 'Listing authors'
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])
    @page_title = 'Details authors'
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new
    @page_title = 'Create new authors'
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
    @page_title = 'Editing authors'
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    load_data
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
  private
  def load_data
    @authors = Author.find(:all)
    @publishers = Publisher.find(:all)
  end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  def index
    @page_title = "Book List"
    @books = Book.all
  end

  def show
  end

  def search
    @page_title = "Search"
  if params[:commit] == "Search" || params[:q]
    @books = Book.find_by_title(params[:q].to_s.upcase)
    end
  end

  def latest
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publishers }
    end
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
    @publisher = Publisher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publisher }
    end
  end

  # GET /publishers/new
  # GET /publishers/new.json
  def new
    @publisher = Publisher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publisher }
    end
  end

  # GET /publishers/1/edit
  def edit
    @publisher = Publisher.find(params[:id])
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(params[:publisher])

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'Publisher was successfully created.' }
        format.json { render json: @publisher, status: :created, location: @publisher }
      else
        format.html { render action: "new" }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publishers/1
  # PUT /publishers/1.json
  def update
    @publisher = Publisher.find(params[:id])

    respond_to do |format|
      if @publisher.update_attributes(params[:publisher])
        format.html { redirect_to @publisher, notice: 'Publisher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy

    respond_to do |format|
      format.html { redirect_to publishers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<p>Online bookstore located in downtown Manhattan, New York</p>
<h2>Mailing Address</h2>
<address>
Emporium<br/>
P.O. Box 0000<br/>
Grand Cayman, Cayman Islands<br/>
</address>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Task</th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.first_name %></td>
    <td><%= author.last_name %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @author.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @author.last_name %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <p><label for="book_publisher">Publisher</label><br/>
<%= collection_select :book, :publisher_id, @publishers, :id, :publisher %></p>
<p><label for="book[author_ids][]">Authors</label><br/>

<%= select_tag 'book[author_ids][]',
      options_from_collection_for_select(@authors, :id, :name,@book.authors.collect{|author| author.id}),
        { :multiple => true, :size => 5 }
%>
</p>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :blurb %><br />
    <%= f.text_area :blurb %>
  </div>
  <div class="field">
    <%= f.label :page_count %><br />
    <%= f.number_field :page_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Publisher</th>
    <th>Published at</th>
    <th>Isbn</th>
    <th>Blurb</th>
    <th>Page count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.publisher_id %></td>
    <td><%= book.published_at %></td>
    <td><%= book.isbn %></td>
    <td><%= book.blurb %></td>
    <td><%= book.page_count %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Publisher</b>
  <%= @book.publisher.publisher %>
</p>

<p>
  <b>Published at:</b>
  <%= @book.published_at %>
</p>
<b>Authors</b>
  <dd><%= @book.authors.collect{|author| author.name }.join(', ') %></dd>
<p>
  <b>Isbn:</b>
  <%= @book.isbn %>
</p>

<p>
  <b>Blurb:</b>
  <%= @book.blurb %>
</p>

<p>
  <b>Page count:</b>
  <%= @book.page_count %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/catalog/_books.html.erb
<dl id="books">
  <% for book in @books %>
    <dt><%= link_to book.title.t, :action => "show", :id => book %></dt>
      <dd><%= pluralize(book.page_count, "page") %></dd>
      <dd><small>Publisher: <%= book.publisher %></small></dd>
  <% end %>
</dl>

app/views/catalog/_search_box.html.erb
<%= form_tag({:action => "search"}, {:method => "get"}) %>
<%= text_field_tag :q %>
<%= submit_tag "Search" %>
<%= form_tag %>

app/views/catalog/index.html.erb
<dl id="books">
  <p><%= link_to "Search", :action => "search" %></p>
  <%= render :partial => "search_box" %><br/>
  <% @books.each do |book| %>
      <%= link_to book.title, book %>
      <dd><%= pluralize(book.page_count, "page") %></dd>
      <dd><small>Publisher: <%= book.publisher_id %></small></dd>
  <% end %>
</dl>

app/views/catalog/latest.html.erb
<h1>Catalog#latest</h1>
<p>Find me in app/views/catalog/latest.html.erb</p>

app/views/catalog/search.html.erb
<%= render :partial => "search_box" %>

app/views/catalog/show.html.erb
<h1>Catalog#show</h1>
<p>Find me in app/views/catalog/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title><%= @page_title || 'Emporium' %></title>
    <%= stylesheet_link_tag "scaffolds" %>
      <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  </head>
  <body>
  <h1>
    <%= "#{@page_title}" if @page_title %></h1>
    <%= yield %>
  </body>
</html>

app/views/publishers/_form.html.erb
<%= form_for(@publisher) do |f| %>
  <% if @publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
      <% @publisher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publishers/edit.html.erb
<h1>Editing publisher</h1>

<%= render 'form' %>

<%= link_to 'Show', @publisher %> |
<%= link_to 'Back', publishers_path %>

app/views/publishers/index.html.erb
<h1>Listing publishers</h1>

<table>
  <tr>
    <th>Publisher</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @publishers.each do |publisher| %>
  <tr>
    <td><%= publisher.publisher %></td>
    <td><%= link_to 'Show', publisher %></td>
    <td><%= link_to 'Edit', edit_publisher_path(publisher) %></td>
    <td><%= link_to 'Destroy', publisher, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Publisher', new_publisher_path %>

app/views/publishers/new.html.erb
<h1>New publisher</h1>

<%= render 'form' %>

<%= link_to 'Back', publishers_path %>

app/views/publishers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>publisher:</b>
  <%= @publisher.publisher %>
</p>


<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', publishers_path %>